[package]
name = "iot-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "iot_rust"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
esp-idf-sys = { version = "0.35", features = ["binstart"] }
